### ISSUE TITLE
packet issue

### ISSUE THREAD

**Issue by Sulferix** [TheSlayerMC/JITL#17]
This mod catastrophically fails in my modpack. every time i die i get the following error: 
![image-1](https://github.com/user-attachments/assets/77cc7887-5e6c-4b02-865d-998ef0f4f016)
there is absolutely no reference to this mod causing the issue in the error text: 
![image](https://github.com/user-attachments/assets/d28b9693-e993-485d-a967-774ed8f3752e)
[latest.log](https://github.com/user-attachments/files/16656300/latest.log)

same result with any forge version. running 1.20.1 version 2.1.6

**Comment by AllShamNoWow101** [comment]
Looks like it may be AOA

![image](https://github.com/user-attachments/assets/89c43280-1f1b-415a-8456-ed3d0cf3b71e)

**Comment by Tslat** [comment]
This is just AoA being the coincidental messenger of an already-existing issue.

AoA itself is not the problem, this is caused by some mod improperly registering a recipe, or improperly returning the recipetype or serializer from a recipe.

You will need to investigate which mod specifically is crashing here when placed with AoA, then get that mod fixed.
Removing AoA is also not a fix, because the next mod that happens to check recipes will crash it all the same anyway
